DROP TABLE IF EXISTS USER;
DROP TABLE IF EXISTS STAGE;
DROP TABLE IF EXISTS INTERVIEW;
CREATE TABLE USER (
  user_id LONG AUTO_INCREMENT PRIMARY KEY,
  first_name VARCHAR(250) NOT NULL,
  last_name VARCHAR(250) NOT NULL
);

CREATE TABLE STAGE (
  stage_id LONG AUTO_INCREMENT PRIMARY KEY,
  stage_name VARCHAR(250) NOT NULL
);

CREATE TABLE INTERVIEW (
  interview_Id LONG AUTO_INCREMENT PRIMARY KEY,
  interview_name VARCHAR(250) NOT NULL
);